services:
    redis:
        image: redis:latest
        volumes:
            - ./data/redis:/data
        restart: always

    web:
        build:
            dockerfile: Dockerfile
            context: .
        env_file:
            - .env
        depends_on:
            - redis
        ports:
            - "8000:8000"

version: "3"
