services:
    redis:
        image: redis:latest
        volumes:
            - ./data/redis:/data
        restart: unless-stopped

    web:
        build:
            dockerfile: Dockerfile
            context: .
        env_file:
            - .env
        depends_on:
            - redis
        ports:
            - "8000:8000"
        restart: unless-stopped

version: "3"
